## 📄 Wildfire Scenario Loading Documentation

The library provides two primary methods for loading wildfire scenarios, depending on the data format: `.npy` for loading from a NumPy binary file and `.jpg` for loading a wildfire scenario from a sequence of grayscale JPG images.. Both return the scenario as a NumPy array.

---

## Supported Formats

#### NPY Format

Use the `load_scenario_npy` function to load scenarios stored as `.npy` files. This format is ideal when **all timesteps are saved in a single array**, making it fast and efficient for loading large datasets.

#### JPG Format

Use the `load_scenario_jpg` function to load scenarios represented as **sequences of grayscale `.jpg` images**, where **each image corresponds to a timestep**. This format is helpful for visual inspection or when the scenario is generated frame by frame.

---

### 🔧 Available Functions

### `load_scenario_npy(filename: str) -> np.ndarray`

**Description:**  
Loads a wildfire scenario from a single `.npy` file.

**Parameters:**
- `filename` *(str)* – Path to the `.npy` file.

**Returns:**
- `np.ndarray` – A NumPy array representing the full scenario over time.

---

#### `load_scenario_jpg(folder_path: str, binary: bool = True, first_frame_only: bool = False) -> np.ndarray`

**Description:**  
Loads a wildfire scenario from a folder containing a sequence of grayscale `.jpg` images.

**Parameters:**
- `folder_path` *(str)* – Path to the folder containing `.jpg` images.
- `binary` *(bool, optional)* – If `True`, applies a threshold at 0.5 to convert images into binary format (burned/unburned). Defaults to `True`.
- `first_frame_only` *(bool, optional)* – If `True`, only the first frame is loaded. Useful for previewing the scenario. Defaults to `False`.

**Returns:**
- `np.ndarray` – A NumPy array representing the scenario (full sequence or first frame).

---

### ✅ Summary

| Format | Function | Input | Use Case |
|--------|----------|-------|----------|
| `.npy` | `load_scenario_npy` | Single `.npy` file | Efficient loading of full datasets |
| `.jpg` | `load_scenario_jpg` | Folder of images | Step-by-step scenario loading, easier visualization |

---


In [1]:
# Example Code: Loading Scenarios
# This script demonstrates how to load scenarios from NPY and JPG files.


# Import necessary modules
import sys
import os
import numpy as np


module_path = os.path.abspath("..") + "/code"
if module_path not in sys.path:
    sys.path.append(module_path)
    print(f"Added {module_path} to sys.path")

from dataset import load_scenario_npy, load_scenario_jpg

# Define paths to the scenario files
scenario_npy_file = "../MinimalDataset/0001/burn_map.npy"
scenario_jpg_folder = "../MinimalDataset/0001/Satellite_Images_Mask/0001_00001/"

# Load scenario from NPY file
scenario_npy = load_scenario_npy(scenario_npy_file)
print("Scenario loaded from NPY file:")
print(f"Shape: {scenario_npy.shape}")
print(scenario_npy)

# Load scenario from JPG images
scenario_jpg = load_scenario_jpg(scenario_jpg_folder, binary=True, first_frame_only=False)
print("\nScenario loaded from JPG images:")
print(f"Shape: {scenario_jpg.shape}")
print(scenario_jpg)




Added /Users/josephye/Desktop/UROP/wildfire_drone_routing/code to sys.path
Scenario loaded from NPY file:
Shape: (72, 116, 287)
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0

Expected Output
Scenario from NPY File:

A NumPy array with shape (T, N, M) where T is the number of timesteps, and N, M are the spatial dimensions.
Scenario from JPG Images:

A NumPy array with shape (T, N, M) where T is the number of timesteps, and N, M are the spatial dimensions.